#!/usr/bin/env python
# import datetime
from datetime import datetime, timedelta
now = datetime.now()

if now.strftime('%a') == 'Sat':
    now -= timedelta(days=1)
if now.strftime('%a') == 'Sun':
    now -= timedelta(days=2)

stamp = datetime(now.year, now.month, now.day, 9) + (now - datetime(now.year, now.month, now.day))/4
print(stamp.strftime('%a %b %d %H:%M:%S %Y +0900'))
